### ISSUE TITLE
有没有人反馈一下好使吗？

### ISSUE THREAD

**Issue by YoungLuk59** [stackia/ha-deye-dehumidifier#12]
在看除湿机，在犹豫是德业T22A3（可能能接ha）还是欧井225E（明确可以进米家）来着，如果好使的话我就下单德业的了。

**Comment by stackia** [comment]
T22A3 在这个插件支持的型号里，应该是能顺利接入的。

**Comment by SeanChengN** [comment]
就指望作者的插件过日子了，连米家的价格贵一些，打算买德业app的用插件了

**Comment by YoungLuk59** [comment]
插件勉强能用。
除湿机德业是专业的啊，不要想小米了

**Comment by stackia** [comment]
插件有遇到什么问题吗？

**Comment by YoungLuk59** [comment]
没啥大问题，就是功能不是很全，凑合能用。

**Comment by YoungLuk59** [comment]
没事了，只是少一个“干衣模式”，其他功能都能支持。是我HA没调好

**Comment by stackia** [comment]
HomeAssistant 里的 强力/强劲/Boost 模式，实际就是干衣模式
