### ISSUE TITLE
卡在添加集成界面的配置向导了

### ISSUE THREAD

**Issue by Lucas776** [stackia/ha-deye-dehumidifier#21]
hass版本是2024.1，安装在安卓手机alpine里的docker下，然后插件版本是1.4.1，其实也下了之前的历史版本试过，都一样，会一直转圈。
![screenshot_2024-01-20_10-40-25](https://github.com/stackia/ha-deye-dehumidifier/assets/62034312/34f81ef5-91a1-4130-9d66-35608e257d79)

**Comment by stackia** [comment]
可能是你的网络问题。可以考虑更换一下国内pip源（具体可以搜索 homeassistant 更换 pip 源）

**Comment by Lucas776** [comment]
感谢，更改后好了
