### ISSUE TITLE
HA更新到2024.3.0版本后插件1.4.1无法同步数据

### ISSUE THREAD

**Issue by SeanChengN** [stackia/ha-deye-dehumidifier#24]
HA版本：2024.3.0
插件版本：1.4.1
![chrome_oRqT4dJShH](https://github.com/stackia/ha-deye-dehumidifier/assets/20624068/2e4fad3e-2d0c-4d7c-8cee-3ddb49ce326d)
如图11号晚开始，只有在重置插件的时候更新一次，否则数据不更新就是一条平行线
日志中好像没有相关的错误代码
是不是个例

**Comment by stackia** [comment]
我在 HA 2024.3.1 下使用没有遇到这个问题，型号是 E12A3。

可以用官方的 德业智能 app，观察一下上面的温度、湿度是否正常变化？如果官方 app 的数据也不更新的话，那有可能是你的设备或网络问题。

**Comment by SeanChengN** [comment]
> 我在 HA 2024.3.1 下使用没有遇到这个问题，型号是 E12A3。
> 
> 可以用官方的 德业智能 app，观察一下上面的温度、湿度是否正常变化？如果官方 app 的数据也不更新的话，那有可能是你的设备或网络问题。

iot.gz.baidubce.com被当广告拦截了，加白名单后正常了
