### ISSUE TITLE
能否解决一下显示当前模式时“跳动”的问题？

### ISSUE THREAD

**Issue by Leo4242** [stackia/ha-deye-dehumidifier#26]
比方说，当前模式由“自动”模式切换为“正常”模式，偶尔会出现显示的模式在“自动”和“正常”模式之间跳来跳去，然后才稳定下来显示当前的模式

**Comment by stackia** [comment]
尝试修复了一下，更新到 https://github.com/stackia/ha-deye-dehumidifier/releases/tag/v1.4.2 试试看

**Comment by Leo4242** [comment]
> 尝试修复了一下，更新到 https://github.com/stackia/ha-deye-dehumidifier/releases/tag/v1.4.2 试试看

解决了！非常感谢大佬！
