### ISSUE TITLE
更新后无法获取正常的数据

### ISSUE THREAD

**Issue by xssviggo** [stackia/ha-deye-dehumidifier#30]
插件版本：v1.5
ha版本：docker镜像 
core核心：2024.4.3
插件获取数据和德业app数据不一致，长时间不更新且无法控制，app正常控制
![image](https://github.com/stackia/ha-deye-dehumidifier/assets/61963810/f108d929-33b7-4788-b70e-0487470d3e22)

**Comment by stackia** [comment]
可以提供一下日志看看

**Comment by xssviggo** [comment]
[home-assistant_deye_dehumidifier_2024-04-13T12-03-56.936Z.log](https://github.com/stackia/ha-deye-dehumidifier/files/14967276/home-assistant_deye_dehumidifier_2024-04-13T12-03-56.936Z.log)
插件调试日志可以么，系统日志好像和插件不太相关

**Comment by conanyangqun** [comment]
同样的问题。1.5插件，2024.04的ha docker镜像，设备D50A3。虽然能正常添加设备，但是加了设备后的状态并未更新，也无法控制。但是通过德业app可以，显示的状态正常，也可以控制。
旧版本插件（忘记版本）和2023的ha可以正常工作（升级后不能工作）。

**Comment by conanyangqun** [comment]
之前用的是v1.2版本 + 2023年某个版本的ha。今天给除湿机断电复电后，发现无法控制，温湿度显示也不正常。才打算更新的ha和插件。如此来看，并不是插件的问题，而是德业这边更新了服务么？
现在开德业的app，会有个提示：
1. 升级到最新版app。旧版本app可能无法使用设备远程控制功能，影响体验。
2. 将设备关机，断电，再复电。设备会自动升级固件版本。

**Comment by stackia** [comment]
已经确认原因是德业针对一部分设备更新了通信协议。

好消息是新的协议我也逆向出来了，最近有空会更新插件。

**Comment by citratecycle** [comment]
插件版本：v1.5
ha版本：haos 12.2
core核心：2024.4.4
除湿机：T22A3
同样的问题，获取不到正确数据+无法控制

蹲蹲作者大大更新，非常感谢！

**Comment by cnrecall** [comment]
大佬！有空更新一下，南方朋友需要你！

**Comment by Remember2019** [comment]
T22A3无法获取数据，显示为不再提供该实体，辛苦大佬有空更新！十分感谢！！

**Comment by liujingzhou** [comment]
大佬，有空更新下，非常感谢

**Comment by Leo4242** [comment]
> 已经确认原因是德业针对一部分设备更新了通信协议。
> 
> 
> 
> 好消息是新的协议我也逆向出来了，最近有空会更新插件。

大佬，有空请记得更新一下

**Comment by Hugo7th** [comment]
大佬加油啊

**Comment by TshineZheng** [comment]
我说怎么最近怎么不工作了，加油加油

**Comment by animagiq** [comment]
昨天家里停电了，恢复之后就没法用了，家里两台抽湿机都没法控制，期待更新

**Comment by dengke80622** [comment]
> 已经确认原因是德业针对一部分设备更新了通信协议。
> 
> 
> 
> 好消息是新的协议我也逆向出来了，最近有空会更新插件。

能登陆mqtt，但没有回复状态请求

**Comment by Hugo7th** [comment]
> #44 新增了对于新设备协议的适配 @stackia 请审核

nice，日以继夜，翘首以盼，半年了，内心深处要放弃的时候，终于等到大神伸出援手

**Comment by stackia** [comment]
感谢 @sususweet 的贡献。现在可以更新到 v1.6.0 试试看，适配了新的协议。
