### ISSUE TITLE
6/1开始ha不能控制DYD-T22A3

### ISSUE THREAD

**Issue by zslibra** [stackia/ha-deye-dehumidifier#33]
6/1开始发现ha不能控制DYD-T22A3，官方APP控制正常。
日志插件没有报错。
ha版本: 2024.5.5
deye-dehumidifier插件版本: 1.5.0
这个插件非常好用，感谢分享，不能用可惜了，不知道是否德业更新控制协议了。
谢谢

**Comment by conanyangqun** [comment]
@zslibra 估计是德业更新了控制协议，作者正在更新。见 #30

**Comment by zslibra** [comment]
谢谢。
上星期插件还能正常工作的，昨天抽湿机关机再开就发现ha 不能控制了，可能是抽湿机自动更新固件版本就不行了。

**Comment by liujingzhou** [comment]
同样的问题

**Comment by Leo4242** [comment]
我也一样

**Comment by Leo4242** [comment]
> 谢谢。
> 
> 上星期插件还能正常工作的，昨天抽湿机关机再开就发现ha 不能控制了，可能是抽湿机自动更新固件版本就不行了。

怎么防止自动更新固件？

**Comment by sususweet** [comment]
方便的话可以把这台机器分享给我，或加下我wx，可以细聊
sususweetcandy

**Comment by stackia** [comment]
现在可以更新到 v1.6.0 试试看，适配了新的协议。

感谢 @sususweet 的贡献。
