### ISSUE TITLE
好像不能同步状态了？

### ISSUE THREAD

**Issue by itispip** [stackia/ha-deye-dehumidifier#34]
我不确定是不是我记错了，但我记得以前，就算是在机器上手动关闭/打开机器，HomeAssistant里面的状态也会同步。

前几天重装了Home Assistant Server，突然发现好像状态不能同步了？

如果通过插件在HA里打开/关闭，状态还是能同步的。就只是在机器上手动关闭/打开的话，会不能同步。

是不是新版本现在在entity status off的情况下，就不会每10秒向服务器请求一次状态码了？我自己在HA里面做了个automation，每10秒publish一个请求才又恢复了同步。

**Comment by sususweet** [comment]
方便的话请提供一下机型
