### ISSUE TITLE
求求作者更新版本，没有homekit很不习惯

### ISSUE THREAD

**Issue by chuchonkit** [stackia/ha-deye-dehumidifier#35]

**Comment by sususweet** [comment]
请给下具体的型号，好针对性做适配

**Comment by sususweet** [comment]
> > 请给下具体的型号，好针对性做适配
> > D50A3，感谢

我手头上没这台机器，方便的话加下我wx，可以细聊
![微信图片_20241212210110](https://github.com/user-attachments/assets/d60230d4-e10e-44d7-a747-f798fd216094)

**Comment by stackia** [comment]
现在可以更新到 v1.6.0 试试看，适配了新的协议。

感谢 @sususweet 的贡献。
