### ISSUE TITLE
感谢大佬开发，但现在无法使用

### ISSUE THREAD

**Issue by firefox167** [stackia/ha-deye-dehumidifier#38]
无法进行控制，如果可以，感谢更新一下，谢谢

**Comment by sususweet** [comment]
方便的话可以把这台机器分享给我，或加下我wx，可以细聊
sususweetcandy

**Comment by stackia** [comment]
现在可以更新到 v1.6.0 试试看，适配了新的协议。

感谢 @sususweet 的贡献。
