### ISSUE TITLE
没法用！没法用 ！

### ISSUE THREAD

**Issue by bwsgp** [stackia/ha-deye-dehumidifier#39]
没法用！没法用 ！
待更新！！！！###

**Comment by Leo4242** [comment]
请作者有空就更新一下吧，谢谢

**Comment by sususweet** [comment]
请给下具体的型号，好针对性做适配

**Comment by Leo4242** [comment]
> 请给下具体的型号，好针对性做适配

T22A3

**Comment by sususweet** [comment]
> > 请给下具体的型号，好针对性做适配
> 
> T22A3

我手头上没这台机器，方便的话可以把这台机器分享给我，或加下我wx，可以细聊

**Comment by Leo4242** [comment]
> > > 请给下具体的型号，好针对性做适配
> 
> > 
> 
> > T22A3
> 
> 
> 
> 我手头上没这台机器，方便的话可以把这台机器分享给我，或加下我wx，可以细聊

你发一下WX

**Comment by sususweet** [comment]
> > > > 请给下具体的型号，好针对性做适配
> > 
> > 
> > > 
> > 
> > 
> > > T22A3
> > 
> > 
> > 我手头上没这台机器，方便的话可以把这台机器分享给我，或加下我wx，可以细聊
> 
> 你发一下WX

![微信图片_20241212210110](https://github.com/user-attachments/assets/d60230d4-e10e-44d7-a747-f798fd216094)

**Comment by stackia** [comment]
现在可以更新到 v1.6.0 试试看，适配了新的协议。

感谢 @sususweet 的贡献。
