### ISSUE TITLE
T22A3接入设备类型识别成climate

### ISSUE THREAD

**Issue by zslibra** [stackia/ha-deye-dehumidifier#4]
您好，发现DYD-T22A3接入进来类型是climate，而不是humidifier，但操作看上去也能正常控制。
请问如何才能识别为humidifier？
谢谢

climate.chu_shi_ji

hvac_modes: dry, off, auto
min_temp: 7
max_temp: 35
min_humidity: 25
max_humidity: 80
fan_modes: low, middle, high
preset_modes: none, boost, comfort
current_temperature: 24
current_humidity: 85
humidity: 55
fan_mode: low
hvac_action: off
preset_mode: none
entity_picture: https://deye-cloud.oss-cn-shanghai.aliyuncs.com/profile/1597889877269.png
friendly_name: 除湿机
supported_features: 28

**Comment by stackia** [comment]
因为 home assistant 的 humidifier 不支持风速控制，而 climate 能够支持，所以支持调整风速的型号目前都是按照 climate 接入的。

如果实在想把它变成 humidifier，有个临时的办法，就是找到自己的 python site-packages 目录位置，编辑 libdeye/const.py，这里面有各个型号支持的功能，找到 T22A3，把 fan_speed 部分改成 `"fan_speed": []`，然后重启 home assistant，应该就好了

**Comment by zslibra** [comment]
好的，明白了，谢谢

**Comment by ye4241** [comment]
也遇到一样的问题的，但是我感觉，可以和miot auto 类型的逻辑，做两层控制就好了，也就是剥离humidifier和fan的，这样子就能让设置保持他原本的属性的，以及可以让反接homekit的时候更加友好一些的。因为humidifier在反接的时候，可以自动读取环境湿度相关的sensor。

<img width="341" src="https://github.com/stackia/ha-deye-dehumidifier/assets/6803102/e48c94cf-6904-400e-994a-de326805d917">

**Comment by stackia** [comment]
> 也遇到一样的问题的，但是我感觉，可以和miot auto 类型的逻辑，做两层控制就好了，也就是剥离humidifier和fan的，这样子就能让设置保持他原本的属性的，以及可以让反接homekit的时候更加友好一些的。因为humidifier在反接的时候，可以自动读取环境湿度相关的sensor。 @stackia 
> 
> 
> 
> <img width="341" src="https://github.com/stackia/ha-deye-dehumidifier/assets/6803102/e48c94cf-6904-400e-994a-de326805d917">
> 
> 

已经有多位朋友反馈 climate 带了的不便了，下一个版本我打算把把他拆分成 humidifier+fan

**Comment by stackia** [comment]
https://github.com/stackia/ha-deye-dehumidifier/releases/tag/v1.4.0
在 v1.4.0 已经不再使用 climate，而是拆分成了 humidifier + fan 两个实体。这样接入 HomeKit 后应该会有更好的使用体验。

**Comment by stackia** [comment]
> 更新1.4后 N20A3控制相关的只有fan，没有humidifier <img alt="截屏2023-07-13 22 41 05" width="1293" src="https://user-images.githubusercontent.com/32008256/253313037-ef691a31-a1e2-410a-8c27-ef74e592c50e.png">

日志是否有任何报错呢？

**Comment by ZHuTOdy** [comment]
> > 更新1.4后 N20A3控制相关的只有fan，没有humidifier <img alt="截屏2023-07-13 22 41 05" width="1293" src="https://user-images.githubusercontent.com/32008256/253313037-ef691a31-a1e2-410a-8c27-ef74e592c50e.png">
> 
> 日志是否有任何报错呢？

有的
<img width="1553" alt="截屏2023-07-13 22 46 45" src="https://github.com/stackia/ha-deye-dehumidifier/assets/32008256/8224a7db-19cd-4498-a842-947bc6506b04">

**Comment by ZHuTOdy** [comment]
> @ZHuTOdy 升级到 1.4.1 试试，应该修复了这个问题。有空也建议升级一下最新 homeassistant，2023.7 在 humidifier 上新增了一个[当前状态](https://github.com/home-assistant/architecture/discussions/731)的属性，在 1.4.0 已经支持了这个属性，但是之前没有考虑好向下兼容的问题，所以在你的 homeassistant 上报错了。

非常感谢，已经解决
