### ISSUE TITLE
作者是不是放弃这个项目了？

### ISSUE THREAD

**Issue by Leo4242** [stackia/ha-deye-dehumidifier#40]
插件不能用好久了

**Comment by stackia** [comment]
我手上的德业除湿机坏了，所以暂时也没有动力更新了😂

**Comment by cnrecall** [comment]
> 我手上的德业除湿机坏了，所以暂时也没有动力更新了😂

大佬！好多人等着您更新呢！动力一下！

**Comment by zslibra** [comment]
> 我手上的德业除湿机坏了，所以暂时也没有动力更新了😂

可惜了。

**Comment by Leo4242** [comment]
> 我手上的德业除湿机坏了，所以暂时也没有动力更新了😂

有保修赶紧跟官方客服联系保修，不然一拖再拖过了保修期就麻烦了
