### ISSUE TITLE
在插件里开关“童锁”功能也会导致“负离子”跟做相应的反应

### ISSUE THREAD

**Issue by Leo4242** [stackia/ha-deye-dehumidifier#45]
我的除湿机型号是：DYD-T22A3

**Comment by Leo4242** [comment]
请修复一下这个Bug，谢谢

**Comment by sususweet** [comment]
请问场景是不是连续快速点击这两个按钮？如果快速点击的话，确实会有这个问题

**Comment by Leo4242** [comment]
> 请问场景是不是连续快速点击这两个按钮？如果快速点击的话，确实会有这个问题

不是连续快速点击两个按钮

**Comment by sususweet** [comment]
@Leo4242 请用新版测试一下，应该已经修复了

**Comment by Leo4242** [comment]
最新版本这个问题又出现了
