### ISSUE TITLE
第二台机器可被添加但没有状态信息

### ISSUE THREAD

**Issue by dengke80622** [stackia/ha-deye-dehumidifier#46]
感谢大佬更新！！我这里有两台设备，添加后能识别到两台设备，但只有第一台设备有信息。

- 识别到账号下面的两台设备

![image](https://github.com/user-attachments/assets/87b61923-0461-4aaa-ad33-93d79a62ccb9)

- 第一台OK, fan.deye_d0bae4b9a2b4

![image](https://github.com/user-attachments/assets/fc1c6e08-4c68-4fe8-9aa9-10f8c9d14010)

- 第二台没有信息, fan.deye_849dc25ec46e

![image](https://github.com/user-attachments/assets/5a428587-57b1-4fe5-bb30-7c5412434c2a)

- log
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: December 15, 2024 at 17:22:06 (12 occurrences)
Last logged: 09:35:43

Entity fan.deye_z12a3_5279_fan_level (<class 'custom_components.xiaomi_miot.fan.MiotModesSubEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Entity fan.deye_d0bae4b9a2b4_fan (<class 'custom_components.deye_dehumidifier.fan.DeyeFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues
Entity fan.deye_d0bae4b9a2b4_fan (<class 'custom_components.deye_dehumidifier.fan.DeyeFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues
Entity fan.deye_849dc25ec46e_fan (<class 'custom_components.deye_dehumidifier.fan.DeyeFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues
Entity fan.deye_849dc25ec46e_fan (<class 'custom_components.deye_dehumidifier.fan.DeyeFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues

**Comment by stackia** [comment]
感谢 @sususweet 修复，更新到 v1.6.1 试试看

**Comment by dengke80622** [comment]
感谢修复，手动点赞！！lol
