### ISSUE TITLE
在插件里开关“童锁”功能也会导致“负离子”跟着做相应的反应

### ISSUE THREAD

**Issue by Leo4242** [stackia/ha-deye-dehumidifier#52]
最新版本这个问题又出现了

**Comment by sususweet** [comment]
请录个短视频或者动画，本地无法复现

**Comment by Leo4242** [comment]
> 请录个短视频或者动画，本地无法复现

https://github.com/user-attachments/assets/d3965b27-98b9-4e40-8fed-e2d8927fc255

**Comment by Leo4242** [comment]
> > > 请录个短视频或者动画，本地无法复现
> 
> > 
> 
> >  trim.CA986A5C-800D-41C8-B123-DDB7073BD939.MOV 
> 
> > 官方App里的那个开关操作动画是我手动在插件里点击“童锁”后自动展示的操作，不是我在官方App里手动点击的
> 
> 
> 
> 此情况为官方App刷新速度和UI显示的问题，需要向官方反馈。请以官方App最终显示的状态为准。此Issue不属于本项目覆盖范围。

不是刷新速度的问题，看一下另外一个视频就知道了https://github.com/user-attachments/assets/99807ee0-9cdd-439f-8546-7c3a0f5fa3ac

**Comment by sususweet** [comment]
多次尝试均无法复现，请尝试重新启动HA，或重新卸载插件后再加载。如还有问题再反馈。

**Comment by Leo4242** [comment]
> 多次尝试均无法复现，请尝试重新启动HA，或重新卸载插件后再加载。如还有问题再反馈。

冷重启HAOS解决了
