### ISSUE TITLE
下次更新建议

### ISSUE THREAD

**Issue by Leo4242** [stackia/ha-deye-dehumidifier#53]
下次更新请顺便把插件显示功能名称显示顺序跟官方App的一致，方便利用通过跟官方App对比找出问题时不会混乱
![image](https://github.com/user-attachments/assets/fd7cc788-485b-4634-a6c8-8b88e2725475)

**Comment by sususweet** [comment]
按钮顺序是用户自己改变lovelace面板来调整的，不是插件决定的。
![Snipaste_2024-12-24_21-30-24](https://github.com/user-attachments/assets/cd6b8aab-b063-4de1-b15b-bec3b77bfc1f)
![image](https://github.com/user-attachments/assets/e8063461-1777-4ce0-9277-5d4e045ce50e)

**Comment by sususweet** [comment]
Close #53. Not a issue.

**Comment by Leo4242** [comment]
> 按钮顺序是用户自己改变lovelace面板来调整的，不是插件决定的。
> 
> ![Snipaste_2024-12-24_21-30-24](https://github.com/user-attachments/assets/cd6b8aab-b063-4de1-b15b-bec3b77bfc1f)
> 
> ![image](https://github.com/user-attachments/assets/e8063461-1777-4ce0-9277-5d4e045ce50e)
> 
> 

这个我知道。我说的不是lovelace面板，我说的设备信息界面

**Comment by sususweet** [comment]
> > 按钮顺序是用户自己改变lovelace面板来调整的，不是插件决定的。
> > ![Snipaste_2024-12-24_21-30-24](https://private-user-images.githubusercontent.com/8524289/398421494-cd6b8aab-b063-4de1-b15b-bec3b77bfc1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDkzNjgsIm5iZiI6MTczNTA0OTA2OCwicGF0aCI6Ii84NTI0Mjg5LzM5ODQyMTQ5NC1jZDZiOGFhYi1iMDYzLTRkZTEtYjE1Yi1iZWMzYjc3YmZjMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxZWUxZWY4NjVjNzRjNzc4NDdkMzk3YWFhZThjYzRjZWM2Zjg2ZThiY2U2YzQxMDc0YTkxZTU4ZmM3NmQwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zki-CahpjTyZA4tfCRXX6ImMWxeNxVuk4A91yPE0VJg)
> > ![image](https://private-user-images.githubusercontent.com/8524289/398421501-e8063461-1777-4ce0-9277-5d4e045ce50e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDkzNjgsIm5iZiI6MTczNTA0OTA2OCwicGF0aCI6Ii84NTI0Mjg5LzM5ODQyMTUwMS1lODA2MzQ2MS0xNzc3LTRjZTAtOTI3Ny01ZDRlMDQ1Y2U1MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzljM2Q4ZTJhNzU1OTRjNzJiZTdmNzVjOTYyMGQwNDZhZmRiYTIwNDM5ZDFlYTMzMDcyNGZhYTg0YWE3OTUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9qdZ-xeYxDWBvDD_52JOnEJMSf673FJWVg8GDG9HA5k)
> 
> 这个我知道。我说的不是lovelace面板，我说的设备信息界面

是哪个界面？设备信息界面应该是HA根据自己的逻辑显示的，外部修改不了

**Comment by Leo4242** [comment]
> > > 按钮顺序是用户自己改变lovelace面板来调整的，不是插件决定的。
> 
> > > ![Snipaste_2024-12-24_21-30-24](https://private-user-images.githubusercontent.com/8524289/398421494-cd6b8aab-b063-4de1-b15b-bec3b77bfc1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDkzNjgsIm5iZiI6MTczNTA0OTA2OCwicGF0aCI6Ii84NTI0Mjg5LzM5ODQyMTQ5NC1jZDZiOGFhYi1iMDYzLTRkZTEtYjE1Yi1iZWMzYjc3YmZjMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxZWUxZWY4NjVjNzRjNzc4NDdkMzk3YWFhZThjYzRjZWM2Zjg2ZThiY2U2YzQxMDc0YTkxZTU4ZmM3NmQwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zki-CahpjTyZA4tfCRXX6ImMWxeNxVuk4A91yPE0VJg)
> 
> > > ![image](https://private-user-images.githubusercontent.com/8524289/398421501-e8063461-1777-4ce0-9277-5d4e045ce50e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDkzNjgsIm5iZiI6MTczNTA0OTA2OCwicGF0aCI6Ii84NTI0Mjg5LzM5ODQyMTUwMS1lODA2MzQ2MS0xNzc3LTRjZTAtOTI3Ny01ZDRlMDQ1Y2U1MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzljM2Q4ZTJhNzU1OTRjNzJiZTdmNzVjOTYyMGQwNDZhZmRiYTIwNDM5ZDFlYTMzMDcyNGZhYTg0YWE3OTUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9qdZ-xeYxDWBvDD_52JOnEJMSf673FJWVg8GDG9HA5k)
> 
> > 
> 
> > 这个我知道。我说的不是lovelace面板，我说的设备信息界面
> 
> 
> 
> 是哪个界面？设备信息界面应该是HA根据自己的逻辑显示的，外部修改不了

![image](https://github.com/user-attachments/assets/1461d0b7-bb20-4349-94c4-08f93fb5ef8e)
![image](https://github.com/user-attachments/assets/4afb6bff-aadc-4270-aa59-486db670c605)

**Comment by sususweet** [comment]
> > > > 按钮顺序是用户自己改变lovelace面板来调整的，不是插件决定的。
> > 
> > 
> > > > ![Snipaste_2024-12-24_21-30-24](https://private-user-images.githubusercontent.com/8524289/398421494-cd6b8aab-b063-4de1-b15b-bec3b77bfc1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDkzNjgsIm5iZiI6MTczNTA0OTA2OCwicGF0aCI6Ii84NTI0Mjg5LzM5ODQyMTQ5NC1jZDZiOGFhYi1iMDYzLTRkZTEtYjE1Yi1iZWMzYjc3YmZjMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxZWUxZWY4NjVjNzRjNzc4NDdkMzk3YWFhZThjYzRjZWM2Zjg2ZThiY2U2YzQxMDc0YTkxZTU4ZmM3NmQwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zki-CahpjTyZA4tfCRXX6ImMWxeNxVuk4A91yPE0VJg)
> > 
> > 
> > > > ![image](https://private-user-images.githubusercontent.com/8524289/398421501-e8063461-1777-4ce0-9277-5d4e045ce50e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDkzNjgsIm5iZiI6MTczNTA0OTA2OCwicGF0aCI6Ii84NTI0Mjg5LzM5ODQyMTUwMS1lODA2MzQ2MS0xNzc3LTRjZTAtOTI3Ny01ZDRlMDQ1Y2U1MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzljM2Q4ZTJhNzU1OTRjNzJiZTdmNzVjOTYyMGQwNDZhZmRiYTIwNDM5ZDFlYTMzMDcyNGZhYTg0YWE3OTUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9qdZ-xeYxDWBvDD_52JOnEJMSf673FJWVg8GDG9HA5k)
> > 
> > 
> > > 
> > 
> > 
> > > 这个我知道。我说的不是lovelace面板，我说的设备信息界面
> > 
> > 
> > 是哪个界面？设备信息界面应该是HA根据自己的逻辑显示的，外部修改不了
> 
> 我说的以下这两个界面 ![image](https://private-user-images.githubusercontent.com/120886701/398437120-1461d0b7-bb20-4349-94c4-08f93fb5ef8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQ5MDIsIm5iZiI6MTczNTA1NDYwMiwicGF0aCI6Ii8xMjA4ODY3MDEvMzk4NDM3MTIwLTE0NjFkMGI3LWJiMjAtNDM0OS05NGM0LTA4ZjkzZmI1ZWY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTM2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2Y4Yjg0Yzc2MWVlOGM5MDQxNjkxMTQ1YmI3ZGJjMjkwNTNhOTA2MWNkYWNiNTcwYjU4MTI2MjU2MTAyYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-jeqec57ByFiPFhoBSQcVbegQoYxEOoD-9StC0P6-AY) ![image](https://private-user-images.githubusercontent.com/120886701/398437150-4afb6bff-aadc-4270-aa59-486db670c605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQ5MDIsIm5iZiI6MTczNTA1NDYwMiwicGF0aCI6Ii8xMjA4ODY3MDEvMzk4NDM3MTUwLTRhZmI2YmZmLWFhZGMtNDI3MC1hYTU5LTQ4NmRiNjcwYzYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTM2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODU3MDNhOGFiNmU4M2I1NmU4ZTQ4YmJmNjU5YjlmM2YyNTEzYmVlY2UyMTFjOWE5MTIyNjkwNzAyY2JmNzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oi5v8LT4Db6HfUl5RtwFF9ZERb7k4ZglDVoFnAEpKO4)

这里不是代码能控制的

**Comment by stackia** [comment]
这个排序插件没法控制。HA 是按照名称的字母/拼音顺序排序的。你可以自定义一下名称，加上 `1 - ` `2 - ` 这样的前缀来自定义顺序。

<img width="331" alt="image" src="https://github.com/user-attachments/assets/0642fafb-9236-4d30-87b3-dce33de92b71" />
