### ISSUE TITLE
500 Internal Error on Raspberry Pi 3

### ISSUE THREAD

**Issue by RebelliousWhiz** [stackia/ha-deye-dehumidifier#7]
OS Version: Home Assistant OS 10.2
Home Assistant Core: 2023.5.4
Hardware: Raspberry Pi 3B

**What I observed**

Internal 500 error when trying to add Deye device.

![Screenshot 2023-06-09 at 5 30 05 PM](https://github.com/stackia/ha-deye-dehumidifier/assets/15100865/9b178495-1365-409f-a56d-70951515bbc1)

**Reproduce**
1. HACS up and running correctly.
2. Install ha-deye-dehumidifier.
3. Reboot the whole system.
4. Try to add Deye devices through [Settings] -> [Devices & Services] -> [Add Intergration] -> [Deye Dehumidifier]
5. Here it comes to this screen:
![Screenshot 2023-06-09 at 5 46 16 PM](https://github.com/stackia/ha-deye-dehumidifier/assets/15100865/bea954dc-dd2e-4d25-a63b-af9afae7fa56)
6. After a while, I get this:
![Screenshot 2023-06-09 at 5 30 05 PM](https://github.com/stackia/ha-deye-dehumidifier/assets/15100865/170f9e8d-5a1a-47c1-91f0-bc2478eec88e)

**What I have tried to resolve**

Install, uninstall, reboot the system, etc., still, the problem persists.

Not sure how to fetch the log. Please let me know if further info is required. Thanks!

**Comment by stackia** [comment]
Logs can be found under `Settings -> System -> Logs`, or in your home assistant config directory -> `home-assistant.log`

**Comment by RebelliousWhiz** [comment]
Highly possible was a problem with HA OS on Raspberry Pi 3. I switched to Linux VM HA OS, was working fine.
