### ISSUE TITLE
建议不要使用中文拼音作为entity id

### ISSUE THREAD

**Issue by ye4241** [stackia/ha-deye-dehumidifier#8]
可否考虑设备的product id + mac的部分前缀 做成id，这样子能能确保设备在重载/添加的时候的唯一性。

**Comment by stackia** [comment]
HA 的 entity id 是由 entity name 自动生成的（对于中文会转换成拼音），我们控制不了这个过程。目前只能添加完设备后，手动逐个修改 entity id。

> 这样子能能确保设备在重载/添加的时候的唯一性
HA 内部对于每个 entity 还有 [unique id](https://github.com/stackia/ha-deye-dehumidifier/blob/e51a2169455aed3fa59336d31a0e05768ae19f62/custom_components/deye_dehumidifier/__init__.py#L108) 属性（我们目前是使用 mac 作为 unique id）。在存在 unique id 的情况下，HA 会使用 unique id 作为 entity 唯一标识，所以不用担心这个问题。
只有对于通过 configuration.yaml 配置的 entity，不存在 unique id，这时候 HA 才会使用 entity id 作为唯一标识。

**Comment by ye4241** [comment]
unique id 是ha内部的唯一性的，在反接到homekit的时候，他只会用entity id的，如果不在代码层指定的话，ha会自动指定成设备名的拼音的。
同样的用miot为例，他似乎是实现了device name 和 entity id不同的，但是我没看明白在哪里设置的。

<img width="512" src="https://github.com/stackia/ha-deye-dehumidifier/assets/6803102/7c00a447-e793-44f4-b23a-840ac7493d5f">

**Comment by stackia** [comment]
miot 扩展好像用到了 HA 开发者文档里没有提的一些骚操作实现的，我试试看

**Comment by ye4241** [comment]
当时想过直接用mqtt创建一个假的device，是可以单独设置类似entity_id的属性的，然后让ha自动发现的。但是和custom components 应该差别很大。

https://www.home-assistant.io/integrations/humidifier.mqtt/#object_id

**Comment by stackia** [comment]
https://github.com/stackia/ha-deye-dehumidifier/releases/tag/v1.4.0
在 v1.4.0 加入了这个功能，由我们自己提供 Entity ID 而不是 HA 根据名称来生成。但是仅限新安装的干净环境才能生效。如果以前已经用过了 ha-deye-dehumidifier，HA 还是会选择以前已有的历史 entity ID。如果有需要可以在 entity 的设置里手动修改一下。
